In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Alzheimer_s_Disease_and_Healthy_Aging_Data.csv")
df

,RowId,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Response,...,QuestionID,ResponseID,LocationID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3,Report
0,2016~2016~12~Q27~AGE~AGE_OVERALL~GENDER~MALE,2016,2016,FL,Florida,BRFSS,Mental Health,Lifetime diagnosis of depression,Percentage of older adults with a lifetime dia...,NaN,...,Q27,NaN,12,AGE,AGE_OVERALL,GENDER,MALE,NaN,NaN,NaN
1,2015~2015~66~Q43~AGE~5064~GENDER~MALE,2015,2015,GU,Guam,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,NaN,...,Q43,NaN,66,AGE,5064,GENDER,MALE,NaN,NaN,NaN
2,2018~2018~66~Q18~AGE~5064~GENDER~MALE,2018,2018,GU,Guam,BRFSS,Screenings and Vaccines,Influenza vaccine within past year,Percentage of older adults who reported influe...,NaN,...,Q18,NaN,66,AGE,5064,GENDER,MALE,NaN,NaN,NaN
3,2018~2018~66~Q34~AGE~5064~GENDER~FEMALE,2018,2018,GU,Guam,BRFSS,Overall Health,Prevalence of sufficient sleep,Percentage of older adults getting sufficient ...,NaN,...,Q34,NaN,66,AGE,5064,GENDER,FEMALE,NaN,NaN,NaN
4,2015~2015~16~Q43~AGE~65PLUS~GENDER~FEMALE,2015,2015,ID,Idaho,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,NaN,...,Q43,NaN,16,AGE,65PLUS,GENDER,FEMALE,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178534,2019~2019~9002~Q42~AGE~5064~RACE~HIS,2019,2019,MDW,Midwest,BRFSS,Cognitive Decline,Talked with health care professional about sub...,Percentage of older adults with subjective cog...,NaN,...,Q42,NaN,9002,AGE,5064,RACE,HIS,NaN,NaN,NaN
178535,2019~2019~9003~Q42~AGE~65PLUS~RACE~ASN,2019,2019,SOU,South,BRFSS,Cognitive Decline,Talked with health care professional about sub...,Percentage of older adults with subjective cog...,NaN,...,Q42,NaN,9003,AGE,65PLUS,RACE,ASN,NaN,NaN,NaN
178536,2019~2019~9002~Q42~AGE~65PLUS~RACE~HIS,2019,2019,MDW,Midwest,BRFSS,Cognitive Decline,Talked with health care professional about sub...,Percentage of older adults with subjective cog...,NaN,...,Q42,NaN,9002,AGE,65PLUS,RACE,HIS,NaN,NaN,NaN
178537,2019~2019~9003~Q42~AGE~5064~RACE~BLK,2019,2019,SOU,South,BRFSS,Cognitive Decline,Talked with health care professional about sub...,Percentage of older adults with subjective cog...,NaN,...,Q42,NaN,9003,AGE,5064,RACE,BLK,NaN,NaN,NaN
178538,2019~2019~9004~Q42~AGE~5064~RACE~NAA,2019,2019,WEST,West,BRFSS,Cognitive Decline,Talked with health care professional about sub...,Percentage of older adults with subjective cog...,NaN,...,Q42,NaN,9004,AGE,5064,RACE,NAA,NaN,NaN,NaN

In [4]:
columns = ['RowId', 'Datasource','LocationAbbr', 'Data_Value_Unit','DataValueTypeID','Data_Value_Alt','Data_Value_Footnote_Symbol',
           'Data_Value_Footnote','Data_Value_Type','Geolocation','StratificationCategory1','StratificationCategory2',
          'StratificationCategory3','Stratification3','ClassID','TopicID','QuestionID','ResponseID','LocationID',
           'StratificationCategoryID1','StratificationID1','StratificationCategoryID2','StratificationID2',
           'StratificationCategoryID3','StratificationID3','Report']
df = df.drop(columns,1)
pd.options.display.max_columns = 100
df.head(2)

,YearStart,YearEnd,LocationDesc,Class,Topic,Question,Response,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,Stratification1,Stratification2
0,2016,2016,Florida,Mental Health,Lifetime diagnosis of depression,Percentage of older adults with a lifetime dia...,NaN,10.7,9.4,12.1,NaN,Overall,Male
1,2015,2015,Guam,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,NaN,31.5,23.4,41.0,NaN,50-64 years,Male

In [5]:
df = df.rename({'Stratification1': 'Age', 'Stratification2': 'M/F'}, axis=1)

In [7]:
df['M/F'].replace('Male', 'M',inplace=True)

In [8]:
df['M/F'].replace('Female', 'F',inplace=True)

In [9]:
df['M/F'].value_counts()

Overall                     23013
White, non-Hispanic         22986
Hispanic                    22886
Black, non-Hispanic         22493
Native Am/Alaskan Native    22112
Asian/Pacific Islander      21831
M                           21609
F                           21609
Name: M/F, dtype: int64

In [10]:
df= df.replace('White, non-Hispanic',np.nan)
df= df.replace('Hispanic',np.nan)
df= df.replace('Black, non-Hispanic',np.nan)
df= df.replace('Native Am/Alaskan Native',np.nan)
df= df.replace('Asian/Pacific Islander',np.nan)

In [11]:
df = df.dropna(subset=['M/F'])

In [12]:
df["Age"].value_counts()

65 years or older    22077
50-64 years          22077
Overall              22077
Name: Age, dtype: int64

In [13]:
df= df.replace('Overall',np.nan)

In [14]:
df = df.dropna(subset=['Age'])

In [15]:
import math

def conv(input_str):
    if pd.isnull(input_str):
        return None
    return int(input_str.split("")[0].replace(" ","-"))

df["int_age"] = df["Age"].apply(conv)
print(df["int_age"])

ValueError: empty separator